# Arquivo de configs e variáveis de ambiente em yaml.

vars:
  max_messages: 1000
google:
  auth:
    credentials_file: credentials.json
    token_file: token.json
  services:
    gmail:
      name: gmail
      version: v1


paths:
  keys: organizador_emails/keys
  config_file: ./config.yaml