# Arquivo de configs e variáveis de ambiente em yaml.
google:
  service: gmail
  credentials_file: credentials.json
  token_file: token.json


paths:
  - keys: organizador_emails/keys
  - config_file: ./config.yaml