# Arquivo de configs e variáveis de ambiente em yaml.
google:
  service:
    name: gmail
    version: v1
  credentials_file: credentials.json
  token_file: token.json

paths:
  - keys: organizador_emails/keys
  - config_file: ./config.yaml